### ISSUE TITLE
Probably bannable

### ISSUE THREAD

**Issue by Golem642** [Efadd/Badge-hacks#1]
I'm no Nintendo expert but i bet this is detectable server-side and I've seen some people get banned for infinite free plays online, so it might not be a good idea.
You should warn people about this in your guide, some people might get mad

**Comment by Efadd** [comment]
How would they detect this as the mem edits are local, and would they even care?

Closing, like the servers next March.

**Comment by Golem642** [comment]
> How would they detect this as the mem edits are local, and would they even care?

Mem edits are local sure, but they know how much free plays you're supposed to get
And your badges have a copy stored online, getting this much will be suspicious.
Would they even care ? Probably not, but there might be some kind of auto Anti-Cheat. And i bet ya they're going to do a final banwave of some kind before closing just to annoy Homebrew people

**Comment by Golem642** [comment]
Do as you will tho, just a warning that this might be a thing
